Console.Clear();
Console.Write("Введите значение k1: ");
int k1= Convert.ToInt32(Console.ReadLine());
Console.Write("Введите значение b1: ");
int b1= Convert.ToInt32(Console.ReadLine());
Console.Write("Введите значение k2: ");
int k2= Convert.ToInt32(Console.ReadLine());
Console.Write("Введите значение b2: ");
int b2= Convert.ToInt32(Console.ReadLine());
double x = (b1-b2)/(k2-k1);
double y =k1*x+b1;
Console.WriteLine("("+x+"," + y + ")");